name: Check & Create PR

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    
jobs:
  create-pr-homolog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          
      - name: Create PR dev into homolog
        env:
          repo: ${{ inputs.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            echo $reviewers
            gh pr create -B homolog -H dev --title "Merge branch dev -> homolog - Criado Automatico" --body "Criado Automaticamente" --reviewer Matelz,JoaoVitorBranco,enzosakamoto
            GH_DEBUG=api gh pr edit --add-reviewer MatCMartins
        
  create-pr-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          
      - name: Create PR homolog into prod  
        env:
          repo: ${{ inputs.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            echo $reviewers
            gh pr create -B prod -H homolog --title "Merge branch homolog -> prod - Criado Automatico" --body "Criado Automaticamente" --reviewer Matelz,JoaoVitorBranco,enzosakamoto
            GH_DEBUG=api gh pr edit --add-reviewer MatCMartins
