name: CI Pytest

on:
  workflow_call:

jobs:
  testApp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
      # esse if else é para o caso do PE, onde o requirements-dev se 
      # tornou o requirements-app para melhor separacao
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements-dev.txt ]; then
                pip install -r requirements-dev.txt
            elif [ -f requirements-app.txt ]; then
                pip install -r requirements-app.txt
            else
                echo "Nenhum arquivo requirements encontrado!" && exit 1
            fi
      - name: Runs tests
        run: pytest
        env:
          STAGE: TEST
      - name: Create coverage report
        run: |
          pytest --cov=./src/
        env:
          STAGE: TEST

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
